### PR TITLE
Issue #58 Fix Attempt

### PR DESCRIPTION
**Pull request by Cooperbuilt**
Changing the text formatting to a link format to make the name "clickable" in the "Notify Community" method. 

Original =>  #{@user.name}  

New Format => <@#{@user.name}>

This follows the "Hey <@U024BE7LH|bob>, did you see my file?" method for formatting links from the slack API documentation. 

!!NOT TESTED!!

### CODE REVIEW

**Comment by rickr** [comment]
Hi @cooperbuilt  

It looks like this has made some tests fail. Can you make sure they're all passing so I can merge?

**Comment by rickr** [comment]
Still looks like there's some failing tests. Check out the following locations:
`test/operationcode_bot_test.rb:96`
`test/lib/event/team_join_test.rb:26`

**Comment by Cooperbuilt** [comment]
@rickr I have no earthly idea how to fix this. It keeps failing tests on what should be a simple formatting fix. Ive tested a bunch of variations and the current commit *should* work but doesn't seem to. If you have any suggestions, I am all ears.

**Comment by Cooperbuilt** [comment]
Thank you for being so kind in your comment! I am working on fixing the test, if I can get it passing, I will definitely try and tackle the next one. I want to familiarize myself as much as possible with Travis for future work.

**Comment by Cooperbuilt** [comment]
I think this should work now, at least it passes the eyeball test.

**Comment by rickr** [comment]
All tests are passing…great job!

**Pull request merged**
